[build]
  functions = "functions"

[[redirects]]
  from = "/movie/*"
  to = "/.netlify/functions/videoHandler/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
